# Generated by Django 5.2.6 on 2025-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LianJiaHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='房源标题')),
                ('total_price', models.FloatField(verbose_name='总价(万元)')),
                ('unit_price', models.FloatField(verbose_name='单价(元/平米)')),
                ('district', models.CharField(max_length=50, verbose_name='区域')),
                ('area', models.FloatField(verbose_name='面积(平米)')),
                ('layout', models.CharField(max_length=20, verbose_name='户型')),
                ('xiaoqu', models.CharField(blank=True, max_length=100, verbose_name='小区')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='楼层')),
                ('orientation', models.CharField(blank=True, max_length=10, verbose_name='朝向')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('pic_url', models.URLField(blank=True, max_length=500, verbose_name='图片链接')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='源链接')),
                ('city', models.CharField(default='北京', max_length=20, verbose_name='城市')),
            ],
            options={
                'verbose_name': '链家房源',
                'verbose_name_plural': '链家房源',
                'db_table': 'lianjia_house',
                'indexes': [models.Index(fields=['district'], name='lianjia_hou_distric_445a87_idx'), models.Index(fields=['unit_price'], name='lianjia_hou_unit_pr_142f46_idx')],
            },
        ),
    ]
